name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/demarijm/emx-auto:latest .

      - name: Push Docker Image
        run: docker push ghcr.io/demarijm/emx-auto:latest

      - name: Deploy to Linode
        run: |
          ssh -o StrictHostKeyChecking=no root@your-linode-ip << EOF
          docker pull ghcr.io/demarijm/emx-auto:latest
          docker stop flask-container || true
          docker rm flask-container || true
          docker run -d --name flask-container -p 80:5000 ghcr.io/demarijm/emx-auto:latest
          EOF
